server:
  port: 25060
spring:
  datasource:
    url:  dbaas-db-2314928-do-user-15894374-0.c.db.ondigitalocean.com
    username: {user_name}
    password: {user_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: base